### ISSUE TITLE
workspace setup?

### ISSUE THREAD

**Issue by martingronlund** [rhysd/cargo-husky#18]
```
error: failed to parse manifest at `...`

Caused by:
  virtual manifests do not specify [dev-dependencies]
```

how?

**Comment by TheAncientGoat** [comment]
If you add it as a dependency to any of the `Cargo.toml`workspace members, it should still install the hooks correctly in my experience

**Comment by nyurik** [comment]
This really should be added to the main readme file. Thx!

**Comment by deepanchal** [comment]
You can also add it as a workspace dependency and reference it in one of the crates. The following setup works for me:

#### Root `Cargo.toml`

```toml
[workspace]
default-members = [
  "crates/server",
]
members = [
  "crates/*",
]

[workspace.dependencies]
cargo-husky = { version = "1.5.0", features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"] }
```

#### `crates/server/Cargo.toml`

```toml
[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.11"
# more deps ...

[dev-dependencies]
cargo-husky = { workspace = true } # <--
```

```sh
cargo clean
cargo test
```
